### ISSUE TITLE
Timetable error

### ISSUE THREAD

**Issue by 404azrael** [AntoninHuaut/EtuEDT-Back#15]
Hello Antonin, je suis en TP1.2 en deuxième année et mon TP est le seul pour lequel une erreur se produit lors de la requête d'affichage de l'emploi du temps (c.f https://edt.antoninhuaut.fr/edt/1/1201). Serait-il possible pour toi d'y jeter un coup d'oeil ?

**Comment by AntoninHuaut** [comment]
Salut, je me renseigne pour récupérer le numéro ADE qui à du changer

**Comment by AntoninHuaut** [comment]
https://github.com/AntoninHuaut/EtuEDT-Back/commit/0d9b0907502693c6256f30e9c1df1496ac4ff30d
